include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'build/**'
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    avoid_unnecessary_containers: false
    prefer_const_constructors: false
    