name: CI/CD Pipeline

on:
  push:
    branches: [ "lab8" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        with:
          flutter-version: '3.24.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test test/widget_test.dart

      - name: Build
        run: flutter build web 
      
