name: Windows Build

on:
  push:
    branches: [ "lab8" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows
